CREATE database IF NOT EXISTS SEMILLERO;

USE SEMILLERO;

CREATE TABLE CLIENTE(
	ID_CLIENTE INT(11) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO VARCHAR(40) NOT NULL,
    DIRECCION varchar(40) NOT NULL,
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    PRECIO NUMERIC(10) NOT NULL,
    STOCK NUMERIC(10) NOT NULL,
    PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE FACTURA (
	NUM_FACTURA INT(11) NOT NULL,
    ID_CLIENTE INT(11) NOT NULL,
    PRIMARY KEY (NUM_FACTURA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE DETALLE(
	NUM_DETALLE INT (11) NOT NULL,
    ID_FACTURA INT (11) NOT NULL,
    ID_PRODUCTO INT(11) NOT NULL,
    CANTIDAD INT(11) NOT NULL,
    PRECIO NUMERIC(10) NOT NULL,
    PRIMARY KEY (NUM_DETALLE, ID_FACTURA),
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(NUM_FACTURA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);
CREATE TABLE CLIENTE(  
	ID_CLIENTE INT(11) NOT NULL,     
    NOMBRE VARCHAR(40) NOT NULL,     
    APELLIDO VARCHAR(40) NOT NULL,     
    DIRECCION varchar(40) NOT NULL,     
    PRIMARY KEY (ID_CLIENTE) 
);

insert into cliente values (1, 'Gabriel', 'Suarez', 'Palmira');
insert into cliente values (2, 'Lina', 'Suarez', 'Palmira');
INSERT INTO producto values(1, 'PC', 100000, 12);
insert into factura values (1, 1);
insert into detalle values (1, 1, 1, 15, 15000000); 
insert into factura values (2, 2);
insert into detalle values (2, 2, 1, 4, 400000);

SELECT D.* FROM DETALLE D, FACTURA F, CLIENTE C WHERE C.ID_CLIENTE = F.ID_CLIENTE AND D.ID_FACTURA = F.NUM_FACTURA;

SELECT * FROM FACTURA;
SELECT * FROM DETALLE;
